// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/url-shortening-service/v1/generate": {
            "post": {
                "description": "create shortening url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shorten Url"
                ],
                "summary": "create shortening url",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GenShorteningUrlReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.GenShorteningUrlRes"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/models.UrlProcessingError"
                        }
                    },
                    "409": {
                        "description": "shortening url conflict",
                        "schema": {
                            "$ref": "#/definitions/models.UrlProcessingError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.UrlProcessingError"
                        }
                    }
                }
            }
        },
        "/api/url-shortening-service/v1/getoriginalurl": {
            "post": {
                "description": "get original url by shortening url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shorten Url"
                ],
                "summary": "get original url by shortening url",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetOriginalUrlReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/models.GetOriginalUrlRes"
                        }
                    },
                    "204": {
                        "description": "url not found",
                        "schema": {
                            "$ref": "#/definitions/models.UrlProcessingError"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/models.UrlProcessingError"
                        }
                    },
                    "409": {
                        "description": "shortening url conflict",
                        "schema": {
                            "$ref": "#/definitions/models.UrlProcessingError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.UrlProcessingError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "summary": "health checker API",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "summary": "service version API",
                "responses": {
                    "200": {
                        "description": "0.0.1",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GenShorteningUrlReq": {
            "type": "object",
            "properties": {
                "expiredAt": {
                    "type": "integer"
                },
                "originalUrl": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.GenShorteningUrlRes": {
            "type": "object",
            "properties": {
                "expiredAt": {
                    "type": "integer"
                },
                "originalUrl": {
                    "type": "string"
                },
                "shorteningUrl": {
                    "type": "string"
                }
            }
        },
        "models.GetOriginalUrlReq": {
            "type": "object",
            "properties": {
                "shorteningUrl": {
                    "type": "string"
                }
            }
        },
        "models.GetOriginalUrlRes": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "expiredAt": {
                    "type": "integer"
                },
                "originalUrl": {
                    "type": "string"
                },
                "shorteningUrl": {
                    "type": "string"
                }
            }
        },
        "models.UrlProcessingError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Shortening Url Swagger",
	Description: "this service is for shortening url",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
